version: "3.8"

services:
  chatbot-api:
    build:
      context: .
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
